### ISSUE TITLE
PR for new features

### ISSUE THREAD

**Issue by simon-p-r** [flagarde/openssl-cmake#5]
Hi 

Just wondering whether you want a PR to allow an option to configure either static or shared MSVC runtime and an option to build either shared or static library.  Also I could include [CPM](https://github.com/cpm-cmake/CPM.cmake) to manage downloading source, running patch and doing build.

**Comment by flagarde** [comment]
Hi,

Maybe I will not use these options for my projects by it would be definitively nice to have such features. CPM would be very great too.

Thanks

**Comment by flagarde** [comment]
@simon-p-r I included CPM
